project:
  type: website
  
execute:
  freeze: auto

website:
  favicon: img/logo_tree_horizontal_ERC_square.png
  twitter-card: true
  site-url: https://mindthegap-erc.github.io/
  open-graph: true
  image: "https://mindthegap-erc.github.io/img/logo_tree_horizontal_ERC_square.png"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - href: subpages/ppl.qmd
        text: "People"
      - href: subpages/student_projects.qmd
        text: "Student projects" 
      - href: subpages/science.qmd
        text: "Science"
      - href: subpages/software.qmd
        text: "Software"
      - href: subpages/pub.qmd
        text: "Publications"
      - href: subpages/teaching.qmd
        text: "Teaching"
      - href: subpages/workshops.qmd
        text: "Workshops"
      - href: subpages/archive.qmd
        text: "Archives and repositories"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



