---
title: "Publications"
---

<!--
chicago manual of style 17th ed (author-date)
-->

-   Agiadi, Konstantina, Niklas Hohmann, Elsa Gliozzi, Danae Thivaiou, Francesca R. Bosellini, Marco Taviani, Giovanni Bianucci, et al. 2024. \"The Marine Biodiversity Impact of the Late Miocene Mediterranean Salinity Crisis.\" *Science* 385 (6712): 986--91. <https://doi.org/10.1126/science.adp3703>.

-   Hohmann, Niklas, Joël R. Koelewijn, Peter Burgess, and Emilia Jarochowska. 2024. \"Identification of the Mode of Evolution in Incomplete Carbonate Successions.\" *BMC Ecology and Evolution* 24 (1): 113. <https://doi.org/10.1186/s12862-024-02287-2>.

We've been working on these topics for a while now. Please also check pre-grant publications:

-   Hohmann, N. (2024). [Possible and Impossible Inferences From Reconstructed Evolutionary Processes using Phylogenies as an Example](https://arxiv.org/abs/2403.03000). arXiv:2403.03000

-   De Baets, K., Jarochowska, E., Buchwald, S. Z., Klug, C., & Korn, D. (2022). [Lithology controls ammonoid size distribution](https://doi.org/10.2110/palo.2021.063). PALAIOS, 37(12), 744--754.

-   Hohmann, N. (2022). [Global compilation of surface mixed layer parameters (sedimentation rate, bioturbation depth, mixing intensity) from marine environments: The SMLBase v1.0](https://doi.org/10.3389/feart.2022.1013174). Frontiers in Earth Science, 10.

-   Hohmann, N. (2021). [Incorporating information on varying sedimentation rates into palaeontological analyses](https://doi.org/10.2110/palo.2020.038). *PALAIOS*, *36*(2), 53--67.

-   Nohl, T., Steinbauer, M. J., Sinnesael, M., & Jarochowska, E. (2021). [Detecting initial aragonite and calcite variations in limestone--marl alternations](https://doi.org/10.1111/sed.12885). *Sedimentology*, *68*(7), 3102--3115.

-   Jarochowska, E., Nohl, T., Grohganz, M., Hohmann, N., Vandenbroucke, T. R. A., & Munnecke, A. (2020). [Reconstructing depositional rates and their effect on paleoenvironmental proxies: The case of the Lau Carbon Isotope Excursion in Gotland, Sweden](https://doi.org/10.1029/2020PA003979). *Paleoceanography and Paleoclimatology*, *35*(12), e2020PA003979.
