---
title: "Workshops"
---

We offer workshops on topics related to stratigraphy and paleobiology. Workshops can be held online or on site, please reach out to us if you are interested in one of the workshops.

## Modeling Stratigraphic Paleobiology in R

The fossil record is a joint expression of biological and geological processes. The record of biological events, such as extinction, migration, speciation, can be distorted by stratigraphic architectures, environmental factors, and taphonomy. The core idea of stratigraphic paleobiology is to incorporate knowledge about geological processes shaping these architectures into paleontological analyses to account for stratigraphic biases. Forward modelling is a way to predict and explore how a given geological section, with its gaps and changes in sedimentation rates, will record a hypothetical biological event. It is a powerful tool to formulate stratigraphic null hypotheses about evolutionary dynamics in the fossil record, which can be compared against empirical observations.

In this workshop, we provide an introduction to forward modelling in stratigraphic paleobiology using the `admtools` and `StratPal` packages for R Software. We demonstrate how to develop a modelling workflow that links evolutionary and ecological models (e.g., niche models, trait evolution) with outputs from forward models of carbonate platform evolution (e.g. CarboKitten.jl, CarboCAT). At the end of the workshop, participants will be able to develop their own simulation study that examines how stratigraphic architectures affect paleobiological interpretations (e.g., extinction rates, tempo and mode of evolution) from geological successions.

This workshop is 3-4 h long (incl. breaks) and suitable for Master students, PhDs, and researchers interested in stratigraphic paleobiology. We adjust the level to match that of the workshop participants.

The workshop requires basic knowledge of the R software, but no prior experience in modeling. It is designed to focus on the scientific questions and principles underlying stratigraphic paleobiology rather than coding skills. The workshop materials are available as an Open Educational Resource (OER) [here](https://doi.org/10.5281/zenodo.13769443).

Contact: [Niklas Hohmann](mailto:N.H.Hohmann@uu.nl) and [Emilia Jarochowska](mailto:e.b.jarochowska@uu.nl)

![Example workflow of a model in stratigraphic paleobiology: The sedimentological forward model specifies what facies is deposited where, and how long the gaps are (left). This information is combined with models of biological change specifies what part of the evolutionary history are preserved (bottom right), and the patterns we can observe in the stratigraphic record (top right). Here , the gaps produce artefactual jumps in trait evoltution.](/img/stratpal_workflow_example.png)

## Modeling Carbonate Platform growth using CarboKitten.jl

Stratigraphic forward models permit us to test hypotheses on the structure of the geological record and on the preservation of proxies or biological information. Until now, most stratigraphic forward models focused on marine siliciclastic or terrestrial environments. However, carbonate platforms have entirely different dynamics, as the sediment is "born, not made" and produced mostly *in situ*. Carbonate platforms are also biodiversity hotspots. In this workshop, we present the first Open Source 3D forward model of carbonate platform growth using [`CarboKitten.jl`](https://mindthegap-erc.github.io/CarboKitten.jl/), written in a new language [Julia](https://julialang.org/), developed specifically for high-performance scientific applications.

In this workshop, we will cover:

- a very short intro to stratigraphic forward modeling with example applications tailored to the audience

- a short intro to running Julia code and explanation why Julia was chosen for this project and how it can be used for other scientific applications

- a hands-on session with `CarboKitten.jl` to model carbonate platform growth and explore the effects of different parameters on the resulting stratigraphy

- extracting data from the model, visualizing it and coupling with other packages in R or Python, depending on the needs of the audience

The workshop does not require any prior knowledge of Julia, but basic knowledge of R or Python will be helpful. We assume prior familiarity with the basics of carbonate sedimentology (at the level e.g. of Schlager's (2005) textbook) and stratigraphy (e.g. Nichol's "Sedimentology and Stratigraphy" textbook or comparable). The workshop is 3-4 h long (incl. breaks) and suitable for Master students, PhD students, and researchers interested in carbonate platform growth and stratigraphic modeling. We adjust the level to match that of the workshop participants.

Contact: [Xianyi Liu](mailto:x.liu6@uu.nl), [Johan Hidding](mailto:j.hidding@esciencecenter.nl) and [Emilia Jarochowska](mailto:e.b.jarochowska@uu.nl)


